//start grammar
start: _NL* globaldef _NL+ [datadef] textdef
//Productions




globaldef: GLOBALDIR LABELREF
datadef: DATADIR _NL+ dataassign+
dataassign: wordassign
wordassign: LABELDEC WORDDIR dtypeset _NL+

textdef: TEXTDIR _NL+ (codeline _NL)* codeline
codeline: textlabeldec? instruction?
// instruction: instructionlabelonly | instructioninsonly | instructionboth
// instructionlabelonly: LABELDEC
// instructioninsonly: instructionset
// instructionboth: LABELDEC instructionset

textlabeldec: LABELDEC

instruction:  rtypeins | itypeins | btypeins | stypeins | ltypeins

rtypeins: RTYPEOPS REGREF COMMA REGREF COMMA REGREF
itypeins: ITYPEOPS REGREF COMMA REGREF COMMA dtypeset
btypeins: BTYPEOPS REGREF COMMA REGREF COMMA LABELREF
stypeins: SWOPS REGREF COMMA dtypeset? LPAREN REGREF RPAREN
ltypeins: LWOPS REGREF COMMA dtypeset? LPAREN REGREF RPAREN



dtypeset: HEX | INT

///Tokens/

RTYPEOPS:       ADDOPS
        |       SUBOPS
        |       ANDOPS
        |       OROPS
        |       SLLOPS
        |       SRLOPS
        |       SLTOPS

ITYPEOPS:       ADDIOPS
        |       ANDIOPS
        |       ORIOPS
        |       SLLIOPS
        |       SRLIOPS
        |       SLTIOPS

BTYPEOPS:       BEQOPS
        |       BNEOPS
        |       BLTOPS
        |       BGEOPS
TYPEDIR.3: WORDDIR

# %import common.NEWLINE -> _NL
_NL: /(\r?\n[\t ]*)+/
%import common.WS_INLINE
%declare _INDENT _DEDENT
%ignore WS_INLINE
// %import .path.to.file


//Tokens
GLOBALDIR.3: ".global"
DATADIR.3: ".data"
TEXTDIR.3: ".text"
WORDDIR.3: ".word"

// ADDOPS.100: "[aA][dD][dD]"
// SUBOPS.100: "[sS][uU][bB]"
// LWOPS: "[lL][wW]"
// SWOPS: "[sS][wW]"
// ADDIOPS: "[aA][dD][dD][iI]"
// SLTOPS:"[sS][lL][tT]"
// SLTIOPS:"[sS][lL][tT][iI]"
// SLLOPS:"[sS][lL][lL]"
// SLLIOPS:"[sS][lL][lL][iI]"
// ANDOPS:"[aA][nN][dD]"
// ANDIOPS:"[aA][nN][dD][iI]"
// OROPS:"[oO][rR]"
// ORIOPS:"[oO][rR][iI]"
// BEQOPS:"[bB][eE][qQ]"
// BNEOPS:"[bB][nN][eE]"
// BLTOPS:"[bB][lL][tT]"
// BGEOPS:"[bB][gG][eE]"


ADDOPS: "ADD"
SUBOPS: "SUB"
LWOPS: "LW"
SWOPS: "SW"
ADDIOPS: "ADDI"
SLTOPS:"SLT"
SLTIOPS:"SLTI"
SLLOPS:"SLL"
SLLIOPS:"SLLI"
SRLOPS:"SRL"
SRLIOPS:"SRLI"
ANDOPS:"AND"
ANDIOPS:"ANDI"
OROPS:"OR"
ORIOPS:"ORI"
BEQOPS:"BEQ"
BNEOPS:"BNE"
BLTOPS:"BLT"
BGEOPS:"BGE"





COMMA: ","

REGREF.3: /x\d+/


LABELREF.1: /[a-zA-Z][0-9a-zA-Z]*/
 
//Data Types
HEX.100: /0[xX][0-9A-Fa-f]{1,8}/
INT.1: /[\+\-]/?/\d/+
LABELDEC.3: /[a-zA-Z][0-9a-zA-Z]*/":"

LPAREN: "("
RPAREN: ")"